# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"
a=s.split()
print(a)

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742
x1="The diameter of {planet} is {diameter} kilometers".format(planet="Earth",diameter="12742")
print(x1)

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])


hello


# Numpy

In [ ]:
import numpy as np


## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
var=np.zeros(10)
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
var1=np.ones(10)*5
var1

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
var=np.arange(20,35,2)
var

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
var=np.arange(0,9).reshape(3,3)
var

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6]) 
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
s1=[1,2,3]
data=pd.DataFrame(s1,columns=['Numbers'])
data


Numbers
0        1
1        2
2        3

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
d=pd.date_range(start='1/1/2023',end='10/2/2023',freq='day')
print(d) 

ValueError: ignored

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
data=pd.DataFrame(lists)
data

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24